### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by costaht** [SubtitleEdit/subtitleedit-cli#1]
Hi, thank you very much for making this headless version. I'm trying to compile it as per instructions but I'm getting the error: 

```
[tijuco@think-fedora subtitleedit-cli]$ ll
total 44
-rw-r--r-- 1 tijuco tijuco 35149 Sep 21 19:30 LICENSE
-rw-r--r-- 1 tijuco tijuco   380 Sep 21 19:30 README.md
-rw-r--r-- 1 tijuco tijuco  1326 Sep 21 19:30 SeCli.sln
drwxr-xr-x 1 tijuco tijuco    12 Sep 21 19:30 src
[tijuco@think-fedora subtitleedit-cli]$ dotnet build SeCli.csproj
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: SeCli.csproj
[tijuco@think-fedora subtitleedit-cli]$ 
```

OS: Fedora release 36 (Thirty Six)

**Comment by costaht** [comment]
Ah, I saw that you were asking for names. Since that is supposed to run on a headless environment, using all lowercase (`secli`) makes things easier to remember and type =) .

**Comment by niksedk** [comment]
@costaht: he, yes. Thx for the suggestion :)
The project file is now called `seconv.csproj` - all lowercase (and no more `/convert` parameter)
