### ISSUE TITLE
How to convert picture based subtitles to .srt?

### ISSUE THREAD

**Issue by GFoley83** [SubtitleEdit/subtitleedit-cli#10]
Title. Looking for a CLI-based way to accomplish this. 
Trying to figure out a way to auto-convert picture based subtitles inside an .mvk as soon as one is added to a particular folder.

**Comment by n00mkrad** [comment]
Not possible. OCR is not included here according to the readme

**Comment by GFoley83** [comment]
Using https://github.com/ratoaq2/pgsrip currently. Works great.
