### ISSUE TITLE
Update to include newer features?

### ISSUE THREAD

**Issue by GOvEy1nw** [SubtitleEdit/subtitleedit-cli#11]
I've moved from Windows to Linux, and as such needed to switch over to this cli version of subtitleedit. However, I've noticed that it hasn't been updated for a while and some of the parameters are missing, compared to the windows version.

Is it possible to update this so it includes the latest CLI features?

Here are the missing parameters that I've noticed:
    
        /assa-style-file:<file name>
        /profile:<profile name>
        /teletextonlypage:<page number>

        /BeautifyTimeCodes
        /ConvertColorsToDialog
        /deletefirst:<count>
        /deletelast:<count>
        /deletecontains:<word>
        /FixCommonErrors
        /RedoCasin
        /SplitLongLines

**Comment by niksedk** [comment]
I've updated what is relatively easy.

"Fix common errors", "profile", and "BeautifyTimeCodes" is difficult without the UI...
