### ISSUE TITLE
The /FixCommonErrors function does nothing

### ISSUE THREAD

**Issue by Gaby13627** [SubtitleEdit/subtitleedit-cli#5]
Hello,
Thank you very much for the availability of this tool.

Is it possible to implement the /FixCommonErrors function to include it in the docker image, because at the moment the part of the code that should be used for that doesn't seem to work and is commentated. I also found no trace of a class comparable to the RemoveTextForHI class, grouping the feature methods, to try to do something similar to how this other class is used.
I don't have much knowledge in the language used by the project and also don't know the structure of the project.

Thanks for your help

**Comment by alexdns1** [comment]
Can confirm

`seconv subs.srt srt /FixCommonErrors /overwrite`

does nothing

**Comment by niksedk** [comment]
It's not really there, so I've removed it from the help

**Comment by kakaska** [comment]
Could you please backport this feature from the main program? That would be awesome if this would be part of the libse. This is a crucial feature if you want to fix multiple subtitles  in batch.

**Comment by bpleao** [comment]
Is it possible to include the original SubtitleEdit application (not subtitleedit-cli) in a docker image to use its cli that provides complete functionality? If so is there a Dockerfile ready for that?

**Comment by bpleao** [comment]
> Is it possible to include the original SubtitleEdit application (not subtitleedit-cli) in a docker image to use its cli that provides complete functionality? If so is there a Dockerfile ready for that?

I suppose this is a solution:
https://github.com/Wauter/subtitle-convert-docker
In my case I don’t mind the 1.5GB size.
