### ISSUE TITLE
Converting to EBUSTL does not work

### ISSUE THREAD

**Issue by iskaj** [SubtitleEdit/subtitleedit-cli#6]
Converting to e.g. .pac or .vtt (and others as well!) works fine, using:
`docker run --rm -it -v $(pwd)/subtitles:/subtitles seconv:1.0 sample.srt pac`
 and
`docker run --rm -it -v $(pwd)/subtitles:/subtitles seconv:1.0 sample.srt WebVTT`
respectively.

However using:
`docker run --rm -it -v $(pwd)/subtitles:/subtitles seconv:1.0 sample.srt EBUSTL`

Gives me the output :
```
Commandline-SE - Batch converter

1: sample.srt -> /subtitles/sample.stl... done.

1 file(s) converted in 00:00:00.1437540
```
But actually no file is created. I've tried digging into the code but I'm not much of a C# guy, so I didn't come up with anything. Copying the latest SubtitleFormats directory gave me build errors. Any ideas?

**Comment by Tomac1** [comment]
I want to join with a similar problem. I am trying to convert subtitles to PacUnicode.
None of these commands work:

```
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.srt PacUnicode 
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt fpc
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt PAC Unicode (UniPac)
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt UniPac
```

I am getting an error: /subtitles/ninja.vtt - target format 'pacunicode' not found!

I will be very happy for a solution.

**Comment by SamuelVanwalleghem** [comment]
Same here with EBUSTL. 1 file(s) converted in xxxx seconds, The file itself is not available at the expected path.
