### ISSUE TITLE
Convert to PacUnicode does not work

### ISSUE THREAD

**Issue by Tomac1** [SubtitleEdit/subtitleedit-cli#7]
I want to join with a similar problem. I am trying to convert subtitles to PacUnicode.
None of these commands work:

docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.srt PacUnicode 
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt fpc
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt PAC Unicode (UniPac)
docker run --rm -it -v ${pwd}/subtitles:/subtitles seconv:1.0 ninja.vtt UniPac
I am getting an error: /subtitles/ninja.vtt - target format 'pacunicode' not found!

This is because of the parentheses in the PacUnicode class name "PAC Unicode (UniPac)", or because it is not listed in CommandLineConverter.cs.

**Comment by Tomac1** [comment]
Please fix the name and remove brackets from the name. I test it locally and it works.

```
namespace seconv.libse.SubtitleFormats
{
    /// <summary>
    /// UniPac
    /// </summary>
    public class PacUnicode : Pac
    {
        public override string Extension => ".fpc";

        public override string Name => "PAC Unicode"; 

        public override bool IsFpc => true;
    }
}
```

**Comment by niksedk** [comment]
Try `seconv a.srt PACUnicode(UniPac)` (Format name without spaces)
Also `fpc` should work as target format

Also, formats just updated a bit
